name: Angular CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'release-candidate/**'
permissions:
  contents: read
  packages: write

jobs:
  angular-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-portal.zip
          path: dist/administration-portal/browser/*
  docker-build:
    runs-on: ubuntu-latest
    needs:
      - angular-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Distribution Directory
        run: sudo mkdir -p /dist/administration-portal/browser
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-portal.zip
          path: /dist/administration-portal/browser/
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'all'
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: docker-metadata-action
        id: docker-metadata-action
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/heimdall-security/admin-portal
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          platforms: 'all'
          tags: ${{steps.docker-metadata-action.outputs.tags}}
          push: true
